name: SILShack Summer 2017

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

future: true

timezone: America/New_York

# You betcha
gems:
  - jemoji

# Categories to exclude from the index
special-categories:
  - "exercise"
  - "how-to"
  - "sidebar"
  - "reading"
  - "notes"

# Exclude Jekyll's built-in tests
exclude: [vendor]

# These can contain uppercase: they'll be lowercased in the URL
page-order:
  - syllabus
  - assignments
  - how-to
  - people

# Same note RE case above
python-extra-pages:
  - console


permalink: none

baseurl: /summer2017
url: /summer2017

python: true

course:
  title: Programming for Information Professionals
  number: INLS 560
  instructor: Prof. Elliott Hauser
  semester: Summer 2017

authors:
  elliott:
    name: Elliott Hauser
    prof: true
    gravatar: 0d0d432948d262195358f339768f1240
    website: http://www.elliotthauser.com
    github: eah13
    twitter: hauspoor
    about:  Elliott Hauser is a PhD Student in information science at UNC Chapel Hill.  He's hacking education as one of the cofounders of Trinket.io.

  tommytester:
    name: Tommy Tester
    prof: false
    gravatar:
    website:
    github: tommytester
    twitter:
    about: "Here's a little about tommytester"

  abaker8:
    name: abaker8
    prof: false
    gravatar:
    website:
    github: abaker8
    twitter:
    about: "Here's a little about abaker8"

  alexreher:
    name: Alex Reher
    prof: false
    gravatar: 
    website:
    github: alexreher
    twitter:
    about: "it's pronounced aboot!"

  anusha-suresh:
    name: anusha-suresh
    prof: false
    gravatar:
    website:
    github: anusha-suresh
    twitter:
    about: "Here's a little about anusha-suresh"

  brianpugsley:
    name: brianpugsley
    prof: false
    gravatar:
    website:
    github: brianpugsley
    twitter:
    about: "Here's a little about brianpugsley"

  businessowl:
    name: businessowl
    prof: false
    gravatar:
    website:
    github: businessowl
    twitter:
    about: "Here's a little about businessowl"

  chall12:
    name: chall12
    prof: false
    gravatar:
    website:
    github: chall12
    twitter:
    about: "Here's a little about chall12"

  chausuble:
    name: chausuble
    prof: false
    gravatar:
    website:
    github: chausuble
    twitter:
    about: "Here's a little about chausuble"

  grassycheetah94:
    name: grassycheetah94
    prof: false
    gravatar:
    website:
    github: grassycheetah94
    twitter:
    about: "Here's a little about grassycheetah94"

  Ibbi2010:
    name: Ibbi2010
    prof: false
    gravatar:
    website:
    github: Ibbi2010
    twitter:
    about: "Here's a little about Ibbi2010"

  jbfelder:
    name: Justyn Felder
    prof: false
    gravatar:
    website:
    github: jbfelder
    twitter: 
    about: "Justyn is a rising Senior at UNC Chapel Hill. He wishes he was creative enough to put more in here but he isn't that creative"

  jmo560:
    name: jmo560
    prof: false
    gravatar:
    website:
    github: jmo560
    twitter:
    about: "Here's a little about jmo560"

  jpanken:
    name: Jaffa
    prof: false
    gravatar:
    website:
    github: jpanken
    twitter:
    about: "Jaffa is a rising second-year MSIS student.  She has lived in 6 different states."  

  kmorbitzer:
    name: Kathryn Morbitzer
    prof: false
    gravatar:
    website:
    github: kmorbitzer
    twitter:
    about: "Kathryn is the lead pharmacist of the data analytics team at UNC Health Care. She is also a Masters student in the Biomedical and Health Informatics program at UNC."

  lisetted:
    name: Lisette Dunham
    prof: false
    gravatar: 
    website:
    github: lisetted
    twitter: ettesild
    about: "Lisette is a Research Data Statistical Analyst at UNC's Lineberger Comprehensive Cancer Center"

  neatoskeeto:
    name: Matt Zimo
    prof: false
    gravatar: fdf561902a98ead21ee2b5f251d44f7c
    website: http://www.oregon-trail-blog.com/
    github: neatoskeeto
    twitter: mattzeemo
    about: "Matt Zimo is an information science grad student at UNC Chapel Hill. Go Vols!"

  nurahill:
    name: nurahill
    prof: false
    gravatar:
    website: 
    github: nurahill
    twitter:
    about: "Here's a little about nurahill"

  nvola:
    name: nvola
    prof: false
    gravatar:
    website:
    github: nvola
    twitter:
    about: "Here's a little about nvola"

  samsr31:
    name: Samuel Robinson
    prof: false
    gravatar:
    website:
    github: samsr31
    twitter:
    about: "Sam Robinson is a second-year MSLS student at UNC Chapel Hill's School of Information and Library Science."

  WildGinger23:
    name: WildGinger23
    prof: false
    gravatar:
    website:
    github: WildGinger23
    twitter:
    about: "Here's a little about WildGinger23"

  zman7895:
    name: zman7895
    prof: false
    gravatar:
    website:
    github: zman7895
    twitter:
    about: "Here's a little about zman7895"



