name: SILShack Summer 2017

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

future: true

timezone: America/New_York

# You betcha
gems:
  - jemoji

# Categories to exclude from the index
special-categories:
  - "exercise"
  - "how-to"
  - "sidebar"
  - "reading"
  - "notes"

# Exclude Jekyll's built-in tests
exclude: [vendor]

# These can contain uppercase: they'll be lowercased in the URL
page-order:
  - syllabus
  - assignments
  - how-to
  - people

# Same note RE case above
python-extra-pages:
  - console


permalink: none

baseurl: /summer2017
url: /summer2017

python: true

course:
  title: Programming for Information Professionals
  number: INLS 560
  instructor: Prof. Elliott Hauser
  semester: Summer 2017

authors:
  elliott:
    name: Elliott Hauser
    prof: true
    gravatar: 0d0d432948d262195358f339768f1240
    website: http://www.elliotthauser.com
    github: eah13
    twitter: hauspoor
    about:  Elliott Hauser is a PhD Student in information science at UNC Chapel Hill.  He's hacking education as one of the cofounders of Trinket.io.

  tommytester:
    name: Tommy Tester
    prof: false
    gravatar:
    website:
    github: tommytester
    twitter:
    about: "Here's a little about tommytester"

  abaker8:
    name: abaker8
    prof: false
    gravatar:
    website:
    github: abaker8
    twitter:
    about: "Here's a little about abaker8"

  alexreher:
    name: Alex Reher
    prof: false
    gravatar: 
    website:
    github: alexreher
    twitter:
    about: "it's pronounced aboot!"

  anusha-suresh:
    name: Anusha Suresh
    prof: false
    gravatar:
    website:
    github: anusha-suresh
    twitter:
    about: "I am currently a rising junior here at UNC. I am hoping to be an INLS major, though I am currently a minor. In regards to this class, I have tried programming several times before with no success, but I am determined to learn something from this course. I love the fall, cookies and cream milkshakes(plus points if it's a malted shake), and jokes (good and bad, mostly)."

  brianpugsley:
    name: Brian Pugsley
    prof: false
    gravatar: 6071e79c795e839e41bbf3cf427b37b8
    website: 
    github: brianpugsley
    twitter: brian_pugsley
    about: "Never half-ass two things. Whole-ass one thing -Ron Swanson"

  businessowl:
    name: Aaron Plocharczyk
    prof: false
    gravatar:
    website:
    github: businessowl
    twitter:
    about: "I am a senior at UNC Chapel Hill taking my last couple courses this summer."

  chall12:
    name: Caroline Hall
    prof: false
    gravatar:
    website:
    github: chall12
    twitter:
    about: "Caroline is a first year Information Science Master's Candidate. She is passionate about renewable energy and the environment. She spends the majority of her time outside of class working for Strata Solar, a national solar farm developer, and United Solar Initiative, an international solar nonprofit."

  chausuble:
    name: chausuble
    prof: false
    gravatar:
    website:
    github: chausuble
    twitter:
    about: "Chausuble is sitting in a chair right now, too sleepy to write anything else."

  grassycheetah94:
    name: Thomas Newlin
    prof: false
    gravatar: da3c08dbb303b7fda7137b1d52e066d6
    website:
    github: grassycheetah94
    twitter: __NEWLIN__
    about: "Thomas Newlin is a MPS student in the Biomedical and Health Informatics program at University of North Carolina-Chapel Hill and a graduate of Indiana University-Bloomington"

  Ibbi2010:
    name: Ayesha Aslam
    prof: false
    gravatar:
    website:
    github: Ibbi2010
    twitter:
    about: "Ayesha Aslam is a physician and a student of Master's program in Health Informatics at UNC"

  jbfelder:
    name: Justyn Felder
    prof: false
    gravatar:
    website:
    github: jbfelder
    twitter: 
    about: "Justyn is a rising Senior at UNC Chapel Hill. He wishes he was creative enough to put more in here but he isn't that creative"

  jmo560:
    name: jmo560
    prof: false
    gravatar:
    website:
    github: jmo560
    twitter:
    about: "Here's a little about jmo560"

  jpanken:
    name: Jaffa
    prof: false
    gravatar:
    website:
    github: jpanken
    twitter:
    about: "Jaffa is a rising second-year MSIS student.  She has lived in 6 different states."  

  kmorbitzer:
    name: Kathryn Morbitzer
    prof: false
    gravatar:
    website:
    github: kmorbitzer
    twitter:
    about: "Kathryn is the lead pharmacist of the data analytics team at UNC Health Care. She is also a Masters student in the Biomedical and Health Informatics program at UNC."

  lisetted:
    name: Lisette Dunham
    prof: false
    gravatar: 
    website:
    github: lisetted
    twitter: ettesild
    about: "Lisette is a Research Data Statistical Analyst at UNC's Lineberger Comprehensive Cancer Center"

  neatoskeeto:
    name: Matt Zimo
    prof: false
    gravatar: fdf561902a98ead21ee2b5f251d44f7c
    website: http://www.oregon-trail-blog.com/
    github: neatoskeeto
    twitter: mattzeemo
    about: "Matt Zimo is an information science grad student at UNC Chapel Hill. Go Vols!"

  nurahill:
    name: Nura Hill
    prof: false
    gravatar:
    website: 
    github: nurahill
    twitter:
    about: "I am a student at UNC. Hoping on soon becoming a official Information Science major! :) "

  nvola:
    name: Natasha Vazquez
    prof: false
    gravatar:
    website:
    github: nvola
    twitter:
    about: "Natasha is an MS student in information science at UNC Chapel Hill and a public health analyst in the Center for Communication Science at RTI International. She likes traveling and beer-ing." 

  samsr31:
    name: Samuel Robinson
    prof: false
    gravatar:
    website:
    github: samsr31
    twitter:
    about: "Sam Robinson is a second-year MSLS student at UNC Chapel Hill's School of Information and Library Science."

  WildGinger23:
    name: WildGinger23
    prof: false
    gravatar:
    website:
    github: WildGinger23
    twitter:
    about: "Here's a little about WildGinger23"

  zman7895:
    name: zman7895
    prof: false
    gravatar:
    website:
    github: zman7895
    twitter:
    about: "Here's a little about zman7895"



